apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: kustomize-app-namespace
  app.kubernetes.io/instance: kustomize-app-namespace
  app.kubernetes.io/name: kustomize-app-name